### ISSUE TITLE
Automated bench DKP

### ISSUE THREAD

**Issue by SamMousa** [ClassicLootManager/ClassicLootManager#10]
Currently bench DKP is a manual process, it would be nice if this can be automated.

These are the steps that need to be done:

1. Load list of players on the bench
2. Verify that each player is eligible for bench DKP.

## Eligibility

Eligibility is probably different per guild, but some things come to mind:

- Must be online at a start time, until an end time. (end time could be end of raid, or just raid full)
- Must be in the raid zone
- Must not be AFK

**Comment by lantisnt** [comment]
Duplicate #24
