### ISSUE TITLE
Add note field to Manual Award

### ISSUE THREAD

**Issue by Peleccotur** [ClassicLootManager/ClassicLootManager#152]
**Issue**
When Manually Awarding DKP there is currently no options to describe what the award (or penalty) was handed out for, which can be confusing long term.

**Solution**
Add a text field to Manual Award option to specify a reason.
Point History should read the description instead of 'Manual Award' unless the description is empty

**Comment by lantisnt** [comment]
Why only to manual?

**Comment by Peleccotur** [comment]
Could go to all, but the other options are descriptive enough imho. Im not against adding it in general, just that my request is for manual

**Comment by lantisnt** [comment]
I think you might be mixing loot and item award. Description is only in point awards

**Comment by Peleccotur** [comment]
Loot and item is the same.
But ye, just reliased that 'Manually Awarding DKP' it called 'Manual Adjustment' or sth like that
Never mentioned loot/items though :-P
