### ISSUE TITLE
Selecting Members in Roster

### ISSUE THREAD

**Issue by Mooslemike** [ClassicLootManager/ClassicLootManager#154]
Would like to be able to click the top raider and shift click the bottom raider on the roster (to select all) and ctrl click to remove individuals. Currently raiders can only be selected one at a time and if you have multiple selected and click on one that has already been selected all raiders are unselected.

**Comment by lantisnt** [comment]
FYI This is a limitation of library we are using for tables

**Comment by lantisnt** [comment]
Covered by #327
