### ISSUE TITLE
Need possibility to award an item without auction

### ISSUE THREAD

**Issue by dmitrysvito** [ClassicLootManager/ClassicLootManager#158]
1. player is targeted
2. go to inventory or dead boss
3. click BIND button
4. little window appears:
https://cdn.discordapp.com/attachments/908748099948793896/909429188660957204/unknown.png

**Comment by SamMousa** [comment]
What does step 2 mean exactly? Afaik looting or opening the loot window changes your target?

**Comment by Peleccotur** [comment]
Yes, looting a boss changes your target. So it would only work this way form your inventory.

Are you aware that the option to award without auction is present, though not in a gui.
Target player -> `/clm award [itemLink]/[value]`

**Comment by SamMousa** [comment]
@dmitrysvito does the answer above solve your problem?

**Comment by lantisnt** [comment]
No user response. Assuming @Peleccotur response is enough
