### ISSUE TITLE
Preparing CLM for localization

### ISSUE THREAD

**Issue by cybertr0nix** [ClassicLootManager/ClassicLootManager#160]
**Is your feature request related to a problem? Please describe.**
As for now addon is available only on english and there is no mechanism available to change language for other language communities.

**Describe the solution you'd like**
Make addon track wow language used and switch to localization file of that language if it is available. If not - keep english.
Localizations can be created by community members. Volunteer for RU local :)
All changes can be made by github pushes.
Addon-wise it will look like DEde.lua , RUru.lua in language folder.

**Describe alternatives you've considered**
none

**Additional context**
For example it's already done within HydraUI the way it's described above.

**Comment by SamMousa** [comment]
Are you up for creating a PR?

**Comment by cybertr0nix** [comment]
> Are you up for creating a PR?

Can you clarify on what you mean by PR here? :)

Adding few lines from pm discussion, before I've created the issue. Hope this will clarify things a bit.

Cyber — Today, at 13:49
<...>
 i was just provided with RUru.lua that i needed to change from english to russian like line to line value -> translation
and i pushed it by small portions on github

Lantis — Today, at 13:51
First of all i need to prepare the localisation code, find all the strings etc and then export to a file, and then yeah that form sounds very good

**Comment by SamMousa** [comment]
PR stands for Pull Request. It means you create the implementation for the translation structure, we can then review it and merge it into our code.

**Comment by cybertr0nix** [comment]
> PR stands for Pull Request. It means you create the implementation for the translation structure, we can then review it and merge it into our code.

Yes sure. It can take some time to finish all the translation and to check it "live" inside game to fix endings etc. , but absolutely up for it.

**Comment by lantisnt** [comment]
This is the initial list of found localisations to be done:
https://docs.google.com/spreadsheets/d/1J2uLzUXQYb7nReuYoDod7qWW5HqOFpDrlNr_IpaVZb8/edit?usp=sharing

**Comment by lantisnt** [comment]
@cybertr0nix please take a look at #175 PR. There is `Locale/ruRU.lua` which you can start looking into :)

**Comment by cybertr0nix** [comment]
> @cybertr0nix please take a look at #175 PR. There is `Locale/ruRU.lua` which you can start looking into :)

Roger roger. Work in progress.

**Comment by cybertr0nix** [comment]
Issue as for 08/12/2021
RU local issue 1: Classes are not translatable. Adding lines to file don't help.
RU local issue 2: Dkp history window - "awarded by" is not linked to "awarded by" line in RUru local file.

**Comment by cybertr0nix** [comment]
Ru local issue 3: Bidding window - Bidding header is not linked to "Bidding" line in RUru local file.
Ru local issue 4: Bidding window - Cancel button is not linked to "Cancel" line in RUru local file.
Ru local issue 5: Bidding window - Pass button is not linked to "Pass" line in RUru local file.

**Comment by cybertr0nix** [comment]
Ru local issue 6: Interface -> Addon Config -> Rosters subtab - "Rosters" both in left menu and header in the right main side is not linked to "Rosters" line in RUru local file.

**Comment by cybertr0nix** [comment]
Issue as for 19/12/2021
Ru local issue 7:  Addon Config -> Roster -> Default slot values -> Base and Maximum over each box are not linked to "Base" and "Maximum" lines in RUru local file.
Ru local issue 8: Addon Config -> General tab -> Changelog header is not linked to "Changelog" line in RUru local file.
Ru local issue 9: Profiles -> Version -> Unknown state is not linked to "Unknown" line in RUru local file.
