### ISSUE TITLE
Alt sorting in Standings out side of Raids

### ISSUE THREAD

**Issue by Rikardp98** [ClassicLootManager/ClassicLootManager#164]
If a guild have players with many alts that they can play with, the standing list can easily become quite "messy" with many rows taken up by alts with the same dkp.  A solution would be to add a "show alts" check box or be able to either left click or right click the main the see their alts. However, I like the fact that the alt is shown when the "in raid" check box is checked!

![Untitled-1](https://user-images.githubusercontent.com/86185671/142629984-ebccad23-3df5-4c7d-98c2-9b7f84fc63c1.png)

This is just an example were the main and alt is shown right next to each other, Aimless for example have one more alt that he can play with, meaning he would take up 3 rows in the standing list. 

To me what's important is the mains dkp, an alts dkp is only important during a raid when that alt is present.

**Comment by lantisnt** [comment]
Closed by #211
