### ISSUE TITLE
Move (or disable) Bid timer and Bid window independently 

### ISSUE THREAD

**Issue by Rikardp98** [ClassicLootManager/ClassicLootManager#179]
**Is your feature request related to a problem? Please describe.**
Many people in the raid would like to be able to move the bid timer bar to the side to be less distracting, but would still like the bid window in the middle. 

**Describe the solution you'd like**
Separate them so one could move them independently.

**Describe alternatives you've considered**
I have also seen some people that would like to disable the timer completely. 
One pretty interesting solution is to give people some option regarding the timer.
Have the bid timer bar enabled
Have the bid timer bar disabled
Add a small count down in the bid window
And maybe an option where you could change the bid timer bar to an icon with similar option to a weak aura.

**Comment by SamMousa** [comment]
What about an single select option for the timerbar:

- disabled
- attached
- detached
- dbm

**Comment by cybertr0nix** [comment]
> What about a single select option for the timerbar:
> 
> * disabled
> * attached
> * detached
> * dbm

just adding a +2 guilds votes here and thats about 150 happy players.
