### ISSUE TITLE
Feature Request: Not In Guild filter/option for the Ranks menu on the Profiles Window

### ISSUE THREAD

**Issue by ridius** [ClassicLootManager/ClassicLootManager#187]
**Is your feature request related to a problem? Please describe.**
I manage our DKP tables and every week, I have to go in and clean-up/remove entries from PuGs. It would make my life much easier to be able to filter out non-guildies.

**Describe the solution you'd like**
A "Not in Guild" option to the Ranks drop down menu that only shows Profiles that are not in guild.

**Describe alternatives you've considered**
Another alternative would be to display Not In Guild in the Rank column of the Profiles window.

**Additional context**
Absolutely LOVE this addon. Just requesting a feature that makes my life easier.

**Comment by SamMousa** [comment]
I like the not in guild option for rank better.

Why do you need to cleanup/ remove entries?

**Comment by ridius** [comment]
We remove non-guildies to make things easier to manage. For example, we only Decay people who miss 4 or more consecutive lockouts. Trying to track that for 50 random people who only ever raided with us once is a pain. Easier to just delete the 1 or 2 profiles of people who aren't in guild each week.

**Comment by SamMousa** [comment]
>  For example, we only Decay people who miss 4 or more consecutive lockouts

If that's the only thing it would make more sense to create a feature request for that ;-)

**Comment by ridius** [comment]
> Isn't the prune cmd enough for that? https://github.com/ClassicLootManager/ClassicLootManager/wiki/4.-Slash-Commands#prune-profiles-of-people-no-longer-in-guild

Prune is great, but we have a couple of "Perma-pugs" that get DO get to keep their DKP. Most we manually clear out at the end of each lockout.
