### ISSUE TITLE
Anti-snipe enhancement for open bidding

### ISSUE THREAD

**Issue by GlodeckWoW** [ClassicLootManager/ClassicLootManager#191]
**Is your feature request related to a problem? Please describe.**
Anti-snipe has a limit of 3 calls to not extend the auction indefinitely. However, this is rarely enough for open-bidding DKP.

**Describe the solution you'd like**
Adding the configurable limit of anti-snipe calls to Rosters -> Auction Settings. Options [checkboxes]: finite or infinite. If finite is checked a value of Custom anti-snipe limit is to be provided.

**Describe alternatives you've considered**
Automatically consider anti-snipe calls limitless if open bidding box is checked.

**Comment by lantisnt** [comment]
@GlodeckWoW what would be a finite, but big enough value for this to work?

**Comment by GlodeckWoW** [comment]
If we speak of alternative options (just an increase in finite number of anti-snipe calls) I guess it depends. In experience have not seen more than 20 last-second bids in a rows. So it might work as a workaround

**Comment by lantisnt** [comment]
My proposal is to keep limit of **3** for closed auctions and semi-unlimited for open. Was thinking about 100.

**Comment by GlodeckWoW** [comment]
Sounds great. And serves great convenience for open auctions. Looking forward to further development of the addon.

**Comment by lantisnt** [comment]
Closed by #194
