### ISSUE TITLE
Interface Optimization: Notes Field

### ISSUE THREAD

**Issue by cybertr0nix** [ClassicLootManager/ClassicLootManager#221]
**Is your feature request related to a problem? Please describe.**
At the moment note field for custom dkp add is small and you are unable to actually see full message in there after dozen on symbols

**Describe the solution you'd like**
Several solutions available from best to worse:
1) Show full text in the field while hoving mouse cursor over the field.
2) Make field flex (auto-changing size) while typing and then back to normal state when you've made addition.
3) Make field bigger statically. Worst option as it will eat space in the menu, while we try to stay minimalistic.

**Additional context**
here.]https://cdn.discordapp.com/attachments/841274229843296256/938779897537658930/unknown.png - current field screenshot

**Comment by lantisnt** [comment]
All GUI requests are to be denied at this point. UI requires general overhaul and no extensions to it are planned at this stage from our pov.

We need to rework whole GUI when the standby feature is done. Any help with reworking it will be appreciated.
