### ISSUE TITLE
Interface Optimization: Bid window minimalistic

### ISSUE THREAD

**Issue by cybertr0nix** [ClassicLootManager/ClassicLootManager#222]
**Is your feature request related to a problem? Please describe.**
At the moment bidding window is "big" and have lots of space that can be optimized.

**Describe the solution you'd like**
One of our masterlooters manually changed his window like this for now, and it looks 1\3 less than current window and i hope this do not  require a lot of work, as we are not adding function, but just change one window. Screenshot below.

**Additional context**
https://cdn.discordapp.com/attachments/841274229843296256/938779964046708776/unknown.png - changes proposal.

**Comment by lantisnt** [comment]
All GUI requests are to be denied at this point. UI requires general overhaul and no extensions to it are planned at this stage from our pov.

We need to rework whole GUI when the standby feature is done. Any help with reworking it will be appreciated.
