### ISSUE TITLE
Items "edit" without new auction

### ISSUE THREAD

**Issue by cybertr0nix** [ClassicLootManager/ClassicLootManager#225]
**Is your feature request related to a problem? Please describe.**
Add the ability to edit item without starting action once again. 
a.    Example 1: raider got item, and second guy went afk and was like oh last peace of set and raider 1 is or with it. Now – we need to delete event, start new auction.
b.    Example 2: raider got item, but after that “oh oh wrong item” and we need to reset it again.
c.    Example 3: raider simply want to pass it to someone who wants it badly after discussion in discord.

Current to do: remove from events, start new auction, ask someone to bid quick again = more spam and more ML work.

**Describe the solution you'd like**
Open loot history -> right click item -> Edit -> change price / player -> save

**Comment by lantisnt** [comment]
I will get later with more discussion but your current solution is invalid.
`Current to do: remove from events, start new auction, ask someone to bid quick again = more spam and more ML work.`

You can actually re-award by clicking on player (while in raid) and typing `/clm award [item link]/value`

**Comment by lantisnt** [comment]
@SamMousa this somewhat corresponds to our `Alt-Right Click` discussion.  I'm starting to think that a lot of this could be solved by adding a award prompt (with dropdown limited only to players in raid). I think I will classify this under the UI rework.
