### ISSUE TITLE
Akama gives double DKP

### ISSUE THREAD

**Issue by cybertr0nix** [ClassicLootManager/ClassicLootManager#226]
**Describe the bug**
Killing Shade of Akama now gives DKP twice.

**To Reproduce**
1. Go to 'Black Temple -> Shade of Akama'.
2. Kill Boss with raid started and option to give dkp on kill.
3. Get 2 kill events on the same second.

**Expected behavior**
Give only 1 kill dkp bonus.

**Screenshots**
https://www.twitch.tv/videos/1284583120?t=1h15m16s - stream of the kill
https://cdn.discordapp.com/attachments/909136808678395954/938888610390876231/unknown.png - DBM screen 1
https://cdn.discordapp.com/attachments/910842442847256647/938893003802697758/unknown.png - DBM screen 2

**AddOn and Game Version:**
 - CLM 1.4.1
 - DBM 2.5.27 alpha  2022/02/01

**Comment by lantisnt** [comment]
[fda3caaee7c14693efa7399ce16eadd2ae162019](https://github.com/ClassicLootManager/ClassicLootManager/commit/70fcf2b17a58122928ee35ff5ac38d49f2484d4b)
