### ISSUE TITLE
Player is not showing up in roster

### ISSUE THREAD

**Issue by NeOxBlitz** [ClassicLootManager/ClassicLootManager#234]
**Describe the bug**
I run a guild and we use CLM one of my guildmembers got banned for his name and forced to name change. Now that he has his new name the addon cannot find him or track his dkp or bids I am having to manually go in and edit his dkp and look up his dkp for him to whisper me bids for gear.

**Expected behavior**
Either be able to track that there was a name change or just register him as a new person and track seperatly and i can update the new name one time and be done with it.

**AddOn and Game Version:**
 Currently on version 1.4.2 but had this issue for a long time now

**Comment by lantisnt** [comment]
No followup. Closing.
