### ISSUE TITLE
Compatibility with Wowup.io

### ISSUE THREAD

**Issue by ridius** [ClassicLootManager/ClassicLootManager#236]
**Is your request related to a problem? Please describe.**
I use a 3rd party addon manager that allows updates directly from GitHub repositories. This manager uses release syntax to to distinguish between Classis Era, TBC, and Retail versions of the client. It will only allow discord updates if the release name ends in -bc

**Describe the solution you'd like**
Can you switch and/or add a release name ending in -bc?

**Describe alternatives you've considered**
None

**Additional context**
Hoping it's not to hard to change build functions.

**Comment by ridius** [comment]
An never mind this issue - it's not with this repository. It's an issue with the addon manager.

**Comment by lantisnt** [comment]
https://github.com/ClassicLootManager/ClassicLootManager/issues/229
