### ISSUE TITLE
Standby list support

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#24]
Allow users to register to standby list. That list would be then used to either manually or automatically to assign standby DKP.

1. Create standby submission CLI / GUI for per roster
2. those players should show up in the **Standby** filter
3.  people in current raid cant be in standby
4. standby list shouldbe cleared after the end of raid

**Comment by SamMousa** [comment]
I think 4 no longer applies. With raids in ledger we should have the standby people in there as well.

3. Should be implemented by changing their status, so we have `join`, `standby` and `leave`.
The last entry decides what you are. So you could go from `join` to `standby` from a history perspective.

**Comment by lantisnt** [comment]
Let's give it a more thought where the standby should be kept. The event bloating is something i am afraid of still.
My concept was to standby be only a temporary information and not kept in the ledger until start of the raid - then a full standby list woudl become part of the ledger

**Comment by lantisnt** [comment]
![image](https://user-images.githubusercontent.com/43088589/140607284-54ff1634-fd9e-49d6-ac03-54bbdcc5b942.png)

**Comment by ridius** [comment]
Wanted to add my +1 to this issue as it's the only functionality CDKP had that's "missing" from how my guild uses DKP.

Also wanted to add a suggestion of an interim feature on the way to full Stand-by automation: could "Standby" simply be people who join the CLM Raid but are not in the actual WoW Raid?

**Comment by lantisnt** [comment]
Proposed solution:
1) Raiders use Raid view to signup to a raid where one wants to be on standby.
 - Raider can be on standby in one raid only
 - Raider can signup only to a  raid in `Created` state - before it is started.
2) Signing up to a Standby happens through addon communication between the signing raider and Raid Owner (Master Looter if present, Raid Leader otherwise).
 - Before Signups are local to the Raid Owner thus any Leader / ML changes need to be done before raid is Created
 - Changing Raid Owner (chgning RL/ML or adding ML) will result in standby list reset
3) New Standby view will be added where Raid Owner will be able to add / remove people from bench
 - Adding to / removing from standby should be possible from roster list when raid is Created or In Progress
4) When raid starts (transitions into In Progress) self-signup standby is locked and commited to the raid status (making standby global) - all further changes need to be done manually by Raid Owner
 - People on standby will be listed and visible in the raid description
 - At this point changing raid owner (RL/ML) will not affect the bench
5) Players joining any raid will be automatically removed from other raids standby

Options to the standby:
A) Automatically move people leaving raid to standby (off by default)
B) Enable / Disable auto award to include players on standby (enable by default)
C) Include everyone on standby / Include only online players (exclude by default)

**Comment by lantisnt** [comment]
Work plan:
1. Core
- [ ] Per-roster configurations
- [ ] Ledger Entry support for bench
- [ ] Mutator support for bench - auto-awarding based on configs
2. Pre-start standby support
- [ ] TBD how this should be implemented internally
3. Ui/UX
- [ ] Option for players to join on standby to created raid
- [ ] Option for Trusted players to add players to standby of the raid they are in
