### ISSUE TITLE
1.5.1 Standby list

### ISSUE THREAD

**Issue by Sah-kage** [ClassicLootManager/ClassicLootManager#253]
Attempting to add player to standby list, release 1.5.1
Player added via standings, right click add to standby.
User disappears from list but does not appear in standby list.
Raid is formed in game, raid leader has officer read/write privs.

Originally standby list option was empty, however after closing and re-opening and was showing standby player. The tooltip showed 0 Standby
![1](https://user-images.githubusercontent.com/86358212/154878966-8bb5154b-5177-4647-973e-43574ba1c796.png)
![2](https://user-images.githubusercontent.com/86358212/154878973-455de046-efce-4af2-a98a-bc5fb6e7fff7.png)

**Comment by lantisnt** [comment]
@Sah-kage Please confirm this works as of `v1.5.2`
