### ISSUE TITLE
Standby Bonus Entries Added to Award History When Standby List Is Empty & Unable To Remove Them

### ISSUE THREAD

**Issue by ridius** [ClassicLootManager/ClassicLootManager#255]
**Describe the bug**
In our latest raid using CLM 1.5.1 we had an Empty Standby List. However, Standby Entries were included for every award even though they applied to no people. When I tried to remove the Standby Entries from the Point History window using Right Click -> Remove Selected nothing happened.

**To Reproduce**
1. Create a Raid with Include bench, Auto bench leavers, Allow subscription enabled and auto-awards turned on
2. Allow auto-awards to happen (start the raid)

**Expected behavior**
I would expect the Point History to not include standby awards if they applied to 0 people (didn't have a standby list).
I would also expect to be able to remove standby entries from the Point History window in case of errors.

**Screenshots**
![Bug Report](https://user-images.githubusercontent.com/1209402/155067325-11cf17d6-dee0-482d-89f2-a49d8e01120a.png)

**AddOn and Game Version:**
 - Game Version: 2.5.3
 - Addon Version: 1.5.1

**Comment by lantisnt** [comment]
@ridius Please confirm this works as of `v1.5.2`

**Comment by ridius** [comment]
@lantisnt Confirmed fixed.
