### ISSUE TITLE
44 / 5.000 Resultados de traducción .lua file for Spanish localization

### ISSUE THREAD

**Issue by Stoytovisiao** [ClassicLootManager/ClassicLootManager#278]
First of all apologies for my English (google translator).
I attach a .lua file with the translations for Spanish.
If possible I would like them to be added to the addon.
Thank you.

Note: The extension has been changed to be able to attach the file.
[esES.txt](https://github.com/ClassicLootManager/ClassicLootManager/files/8458868/esES.txt)

**Comment by lantisnt** [comment]
@Stoytovisiao 
Thank you for the contribution! I have created PR for it #279 however some strings are missing.
Please also join our discord for easier communication of further updates :)
