### ISSUE TITLE
After new version 1.8.0

### ISSUE THREAD

**Issue by Nianne666** [ClassicLootManager/ClassicLootManager#289]
Fast need solve . problem with item auction . permanently says to bidders - Invalid bid value

**Comment by Nianne666** [comment]
hm , install older 1.7.1 . doing same .

**Comment by Nianne666** [comment]
sry , solved on discord , god bless Lantis . thanks for help .

**Comment by Jobjeuh** [comment]
What was the solution? Not everyone is on the discord

**Comment by crimsoncoyote** [comment]
Possible it's due to having static item value set and instead wanting ascending
