### ISSUE TITLE
Class and character name columns can be combined in the standings table.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [ClassicLootManager/ClassicLootManager#291]
**Is your request related to a problem? Please describe.**
No problem. Just an optimization to reduce visual noise.

**Describe the solution you'd like**
For non-colorblind mode the character name text could be wrapped in the class color to reduce visual noise in the standings table.

**Comment by lantisnt** [comment]
What would you propose for colorblind mode though? Since if we wrap the names in color, a removal of class column is natural to follow. And I'm not very fond of having 2 versions of GUI

**Comment by SamMousa** [comment]
Can't sort by colour though, so removing class has downsides for not virtually impaired people as well

**Comment by Chalos-Atiesh** [comment]
That's a good point and this is just one of my personal preferences. Closing.
