### ISSUE TITLE
Toggling the bid window could be easier.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [ClassicLootManager/ClassicLootManager#293]
**Is your request related to a problem? Please describe.**
Most people pass on most bids. I set it to not auto-open the bid window on new bids. Now to open the bid window I have to either use the minimap icon or type `/clm bid`.

**Describe the solution you'd like**
It would be super useful if clicking the timer toggled the bid window.

**Describe alternatives you've considered**
I could create a macro but that's _yet another_ button on my action bars that I rarely use but is required.

**Comment by lantisnt** [comment]
Well you have:
1) /slash command `/clm bid`
2) Mouse clicks `Icon -> RMB-> Bidding`
3) Keybinds (Interface settings)

But since the whole bidding UI will be reworked I'll link this to that issue.

**Comment by lantisnt** [comment]
Will be covered together with #285

**Comment by Chalos-Atiesh** [comment]
Those require multiple key presses, clicks, or yet another keybind. Of which I personally already have far too many. There could be a Bid button next to the timer that opens the bid window. IMO that's the easiest route.

**Comment by lantisnt** [comment]
Will be covered in WoTLK UI rework
