### ISSUE TITLE
Various messages printing to the chat window should be toggleable.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [ClassicLootManager/ClassicLootManager#294]
**Is your request related to a problem? Please describe.**
Some of the messages that are printed to the chat window are helpful. Others are unnecessary.

**Describe the solution you'd like**
One toggle for all messages would kinda work. Though it would filter out the messages that are useful. A toggle for each category of message would be better.

**Comment by lantisnt** [comment]
I'm quite hesitant about this since people don't like to not get feedback of their action, or if they don't get it or miss it they tend to blame an "addon issue". Can you list the messages you deem unnecessary?

**Comment by Chalos-Atiesh** [comment]
After thinking about this more and fiddling with some of the settings I don't think this is necessary. The addon isn't too spammy. Closing.
