### ISSUE TITLE
Clicking any type of 'Submit' button should close the corresponding window.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [ClassicLootManager/ClassicLootManager#295]
**Is your request related to a problem? Please describe.**
The Bid, Pass, Award, etc. buttons do not close their corresponding windows.

**Describe the solution you'd like**
It should close the window when it is highly likely the user is done with that window.

**Comment by lantisnt** [comment]
This is an actual design choice but when reworking the UI I will add an optional config to close the UI after sending a bid.

Will be adressed together with #285.

**Comment by Chalos-Atiesh** [comment]
I want to say I appreciate the amount of thought you're putting into the improvement ideas I'm submitting. It doesn't go unnoticed.

**Comment by lantisnt** [comment]
Will be covered in WotLK UI rework
