### ISSUE TITLE
deDE.lua contains french

### ISSUE THREAD

**Issue by Charadrass** [ClassicLootManager/ClassicLootManager#302]
deDE.lua file
line 1077
current state: CLM.L["Raid [%s] started"] = "Le raid [%s] gestartet"
should be: CLM.L["Raid [%s] started"] = "Raid [%s] gestartet"

**Comment by Saysor** [comment]
i fixed it in my PR. :) @lantisnt

**Comment by lantisnt** [comment]
Fixed by #309
