### ISSUE TITLE
Option to hide Minimap Button

### ISSUE THREAD

**Issue by Desik** [ClassicLootManager/ClassicLootManager#303]
**Is your request related to a problem? Please describe.**
I don't use minimap buttons, instead I have a databroker launcher, I can't find the option to hide CLM minimap button anywhere

**Describe the solution you'd like**
A simple /clm minimap to toggle hide/show the minimap button

**Describe alternatives you've considered**
You could just hide the minimap button with moveanything or similar addons.

**Comment by lantisnt** [comment]
Closed by #321
