### ISSUE TITLE
Marking bids as invalid

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#33]
In bid window right click on bids to mark them as invalid.
Invalid bids need to be grayed out.
All the max/2nd price calculation should skip those

**Comment by lantisnt** [comment]
This should be reviewed as generic Auctioning UI upgrades (Master Looter)

**Comment by SamMousa** [comment]
I don't like magic clicks, use right click for context menu.
Then add a mark as invalid there?

**Comment by lantisnt** [comment]
This is no longer an issue especially with auto-open based on fact if someone can use the item
