### ISSUE TITLE
Profile lock ledger entry improvement

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#350]
Currently, locking or unlocking a profile creates a ledger entry that isn't in a human-readable format.
It displays a set of numbers (object reference? not familiar with lua) followed by `true` or `false` whether the entry locks or unlocks, respectively.
Unfortunately, this means determining which entries correspond to which lock/unlock event can be tedious, difficult, and/or impossible without extensive use of timetravel and comparing changes in the profile/standings tables (especially with a large number of profiles in those tables or being locked/unlocked at once).

Some kind of identifying information in the ledger for lock toggle events would be very helpful.

**Comment by lantisnt** [comment]
No entries are in human readable format, or do you mean Audit?
