### ISSUE TITLE
Make the change log on startup configurable. 

### ISSUE THREAD

**Issue by Rorthron** [ClassicLootManager/ClassicLootManager#352]
Your addon spams all users whenever they log on with a new version. I would say that the changes here are largely irrelevant to most of our guild members. Just make this change log configurable so that Raid Leaders know what has changed. Raid members should not care. 

Also, the change log doesn't say which addon it relates to. It created a whole load of confusion in our guild. Unnecessary spam for 90% of people.

**Comment by crimsoncoyote** [comment]
There's a checkbox in the top left of the changelog window to stop that and an option to disable it in the CLM configuration in Interface>Addons

**Comment by Rorthron** [comment]
Yes, I saw that. Thanks for taking the time to do this update.
