### ISSUE TITLE
Allow Offspec bids via wisper

### ISSUE THREAD

**Issue by Senjiu** [ClassicLootManager/ClassicLootManager#353]
Hey, I just saw that you can now declare bids as offspec. Some people are not using the addon and bid via wisper and don't seem to have that option.

Solutions:
If it is already possible to include the fact that a bid is for offspec in a wisper: maybe add that to the documentation (and/or the raid message when a bid starts, that explains how bidding via wisper works).
If not please add that feature to bidding via wisper.

**Comment by lantisnt** [comment]
Chat commands are a fallback in case someone Has some issues and is not the recommend use case thus they have the bare minimum functionality. You should ask the players to start using CLM if they want to have full support.
