### ISSUE TITLE
Modifier to change automatic standby DKP awarded 

### ISSUE THREAD

**Issue by rivare** [ClassicLootManager/ClassicLootManager#365]
I would like to request an additional feature that allows to modify the automatic DKP awarded to the players on standby. Ideally there could be an slider or input field next to the check box that enables the automatic values for standby ppl. All automatic DKP would then first be multiplied with the modifier (e.g. 0.9) and afterwards awarded.

**Comment by erikabp123** [comment]
Second this feature

**Comment by timj11dude** [comment]
Is this feature not already in CLM?
