### ISSUE TITLE
"Minimum points" setting causing bidding max to fail

### ISSUE THREAD

**Issue by daxxio** [ClassicLootManager/ClassicLootManager#367]
I noticed what seems like a bug in regards to the setting: "Auction settings -> Bidding -> Minimum Points".

We have an ascending item value mode, with bids from 0 to unlimited. We therefore tried setting the "Minimum points" setting to 5, but noticed that this leads to people not being able to bid higher than their current DKP -5. Seems like an unintended interaction, unless I misunderstand the "minimum points to bid" setting.

**Comment by lantisnt** [comment]
That's expected behavior, as it always calculates `new = current - bid < minimum points`.

This settings creates a bottom threshold of points that player needs to have to be able to bid.
There is another setting next to it, that allows people to go below minimum points after bidding.

**Comment by daxxio** [comment]
Ok, just wanted to point out that if you got 21 DKP and you set this setting to 20 DKP. You cannot bid more then 1.

**Comment by lantisnt** [comment]
That's correct, because you didnt enable going below min points. This whole mechanism is generlisation of going negative (below 0)
