### ISSUE TITLE
CLM price shows on all tooltips

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#379]
Currently CLM price is showing on all items when the "show price" option is enabled. This includes items that make no sense, like food, quest items, or hearthstones. Part of this issue is that you cannot set default values for quest items or consumables, etc.

To address this, I suggest configuring it such that only certain items show the tooltips. A quick/dirty fix would be to only show the tooltip price on items over a certain ilvl (Naxx 10 starts at 200, but that would also cause it to show on heroic dungeon items). Ideally, it would only show on raid drops. In addition, it would be nice to have the option to hide the tooltip price when the default base/max values are set to 0, rather than display "any".

Example:
![image](https://user-images.githubusercontent.com/1790997/192573944-77c2f447-9516-42fd-a85b-55861ed5df6b.png)

**Comment by lantisnt** [comment]
I will limit it to equipabble items with ilvl >= 200 as a short win
