### ISSUE TITLE
No Boss Kill DKP from Malygos, Sartharion (and the three Dragons)

### ISSUE THREAD

**Issue by Geronymo17** [ClassicLootManager/ClassicLootManager#383]
In our raid yesterday we didn't receive any boss kill dkp from the Malygos, Shadron, Tenebron, Vesperon and Sartharion kills.

We will try next week again but maybe you could look into it. I would understand why Malygos fails because of the nature of the boss fight but not Sartharions and so on.

We tried it with 10 DKP for Malygos. For Sartharion we tried something different. We gave -2.5 DKP for Shadron, Tenebron and Vesperon and 17.5 DKP for Sartharion. So if you kill him the "normal" way you would end up with 10 DKP again while getting a bonus if you leave some of the dragons alive.

We used v 2.3.1 - 

Thanks for all the work!

**Comment by lantisnt** [comment]
Hi. thanks for the report.

Can you give me more info?
- 10 or 25 man?
- screenshots of your settings: 
  - boss kill bonus enabled / disabled
  - boss kill bonus default value
  - boss kill bonus values for the bossess for both 10 and 25 mans

**Comment by Geronymo17** [comment]
Hi Lantis,

this was the 25-men version for both raids. The boss kill bonus is enabled with default value 0. Maybe the -2.5 DKP are the reason it didn't work. Here are the screenshots.

![Boss_Kill_Bonus_Enabled](https://user-images.githubusercontent.com/57114704/195115889-3cd9ab8a-b8ef-47a4-9aa2-62d2ffab4b69.JPG)
![Boss_Kill_Bonus_10](https://user-images.githubusercontent.com/57114704/195115882-67622469-ac0e-4050-aeca-b8b470ca9958.JPG)
![Boss_Kill_Bonus_25](https://user-images.githubusercontent.com/57114704/195115884-ace1b945-cd15-460a-b82b-ad4e037e0818.JPG)
![Boss_Kill_Bonus_Enabled](https://user-images.githubusercontent.com/57114704/195115889-3cd9ab8a-b8ef-47a4-9aa2-62d2ffab4b69.JPG)

Thanks!

**Comment by lantisnt** [comment]
Did Sartharion and Malygos work?

**Comment by MedericGirard** [comment]
Hi, in my raid tonight dkp have been award but default values and not specific for Sartha and Maly

![image](https://user-images.githubusercontent.com/107113783/195190907-c2b1c653-d082-4306-8a40-95cf526eb9e4.png)


![image](https://user-images.githubusercontent.com/107113783/195190881-24dc75f8-2f88-41fb-b2db-da55190a86eb.png)

**Comment by MedericGirard** [comment]
![image](https://user-images.githubusercontent.com/107113783/195395508-37cf84d4-a92e-4832-bb7d-0a555b5fa01f.png)
We adjust 30pts manually

**Comment by lantisnt** [comment]
@Geronymo17 @MedericGirard I will need to ask you guys to enable and run Transcriptor on those encounters https://www.curseforge.com/wow/addons/transcriptor and give me the logs from it

**Comment by lantisnt** [comment]
Please verify fix with `v2.5.0`

**Comment by MedericGirard** [comment]
It works perfectly thank you
