### ISSUE TITLE
ERROR when bidding using chat commands

### ISSUE THREAD

**Issue by nogi1** [ClassicLootManager/ClassicLootManager#392]
**Describe the bug**
Since the last update 19.10.2022 bidding using chat commands doesn't accept bids and error pops in the chat that there is problem with reading the value. Bidding using addon window works fine.

**To Reproduce**
1. Start auction
2. Let someone bid using chat command !bid value
3. see error in the chat

**Expected behavior**
addon will accept bid using chat commands

**Screenshots**
![image](https://user-images.githubusercontent.com/14179320/197061711-7f14c587-e9ac-44c3-9705-a571f409d7bf.png)

**AddOn and Game Version:**
 - addon v2.5.0-wrath from 19.10.2022
 - game 3.4.0.46158

**Additional context**

**Comment by nogi1** [comment]
Probably broken by commit 08771d11db5e35f5525dfc8293d47a6abb8434e0

**Comment by crimsoncoyote** [comment]
Looks like it might be this https://github.com/ClassicLootManager/ClassicLootManager/blob/master/Modules/AuctionManager/AuctionManager.lua#L474

**Comment by lantisnt** [comment]
Fixed in:
https://github.com/ClassicLootManager/ClassicLootManager/commit/fceca94555db6415e30be67bffbb4aa0d50f7588
