### ISSUE TITLE
Unable to open gui with /clm gui

### ISSUE THREAD

**Issue by cjmoore7** [ClassicLootManager/ClassicLootManager#407]
Getting the following bug in Bugsack when attempting to open CLM
6x ClassicLootManager\Utils.lua:714: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@ClassicLootManager\Utils.lua"]:714: in function `fnDoCellUpdate'
[string "@ClassicLootManager\Libs\lib-st\Core.lua"]:849: in function `Refresh'
[string "@ClassicLootManager\Libs\lib-st\Core.lua"]:856: in function `updateFunction'
[string "@SharedXML\SecureUIPanelTemplates.lua"]:332: in function `FauxScrollFrame_OnVerticalScroll'
[string "@ClassicLootManager\Libs\lib-st\Core.lua"]:856: in function <...rfaceClassicLootManager\Libs\lib-st\Core.lua:855>
[string "=[C]"]: in function `SetVerticalScroll'
[string "@SharedXML\SecureUIPanelTemplates.lua"]:64: in function <SharedXML\SecureUIPanelTemplates.lua:63>
[string "=[C]"]: in function `SetValue'
[string "@SharedXML\SharedUIPanelTemplates.lua"]:218: in function <SharedXML\SharedUIPanelTemplates.lua:212>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by lantisnt** [comment]
Test it with all other addons disabled. Then enable one by one and see which one is creating the error :)

**Comment by cjmoore7** [comment]
I disabled all addon's except for CLM V2.5.5-wrath.zip and still getting the same error when typing /clm gui and scrolling the window

![image](https://user-images.githubusercontent.com/84809784/198393833-db7fd628-8b4d-4006-b7b7-21e58ca86506.png)

**Comment by lantisnt** [comment]
i am not able to reproduce it with CLM only enabled. Can you prove me you have only it enabled?

**Comment by cjmoore7** [comment]
![image](https://user-images.githubusercontent.com/84809784/198397072-442c4462-ae1f-4a55-94d4-ca6cc36df482.png)
![image](https://user-images.githubusercontent.com/84809784/198397117-79904a0b-b49d-41c7-b023-5c1e83a7246c.png)
![image](https://user-images.githubusercontent.com/84809784/198397146-e084f037-63a5-4510-96d0-0bff2cb602cd.png)
![image](https://user-images.githubusercontent.com/84809784/198397205-5f53423e-5a54-4a12-b8b2-c899f90db05b.png)

**Comment by lantisnt** [comment]
what game version are you playing?
locale?
can you record where do you get the error?

**Comment by cjmoore7** [comment]
Game Version: 3.4.0.46248
Text: English
Audio: English

When I slide the scroll bar in this screenshot I get the error:
![image](https://user-images.githubusercontent.com/84809784/198399317-d92b8ad0-d8f0-4537-b64b-9d705ab9f0d9.png)

Then if I close the error and the window I can no longer get the CLM GUI to show up I get a New Error:
![image](https://user-images.githubusercontent.com/84809784/198399460-d3b83c41-dfae-46a9-ba14-16620f02b5c4.png)

Until I reload the game.

**Comment by lantisnt** [comment]
Can you try to do it all very very slowly to check if it happens when you maybe hover over specific row?

**Comment by cjmoore7** [comment]
I reloaded, I was able to mouse over each player in the table and see the popup window, as soon as I clicked the scroll down button, it threw an error.  
I have no issues mousewheeling or clicking up and down on the history tab, raids tab, or the audit tab.

I get errors when trying to view the profiles tab
![image](https://user-images.githubusercontent.com/84809784/198401511-210b5bf3-20b6-44ad-ba44-acd9830c0ee1.png)
only loads partial then errors out, 
![image](https://user-images.githubusercontent.com/84809784/198401556-e00ac740-0ed7-4bb7-9200-0aba7c5deed0.png)

**Comment by lantisnt** [comment]
This one is a great start. It suggests it's data related. We would need to know who does it fail on and why. Pleass upload saved variable so i can try to reproduce it.

**Comment by cjmoore7** [comment]
[ClassicLootManager.zip](https://github.com/ClassicLootManager/ClassicLootManager/files/9883335/ClassicLootManager.zip)

**Comment by lantisnt** [comment]
Just the lua svar please:
`<wow install directory>\_classic_\WTF\Account\<account id>\SavedVariables\<addon name>.lua`

**Comment by cjmoore7** [comment]
Github does not allow for the upload of .lua files, I zipped the file located at "C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\55826435#1\SavedVariables\ClassicLootManager.lua"

**Comment by lantisnt** [comment]
You somehow have a death knight without class information in profile:
![image](https://user-images.githubusercontent.com/43088589/198531355-4d51ba13-9bc9-47fa-a55b-86773e2eabe2.png)
I will add protection for this but you do want to update his profile so he has the class

**Comment by lantisnt** [comment]
Quite few even
![image](https://user-images.githubusercontent.com/43088589/198532071-53cb7a57-992f-4d83-8aab-073159003149.png)
