### ISSUE TITLE
Please allow moving of bidding timer bar after closing bidding window

### ISSUE THREAD

**Issue by Volt-Essential** [ClassicLootManager/ClassicLootManager#42]
**Is your feature request related to a problem? Please describe.**
After you close the bidding window it's no longer possible to move the bidding timer bar

**Describe the solution you'd like**
Please allow the user to move the bidding timer bar after the bidding window is closed

**Describe alternatives you've considered**
I don't see any alternative solution

**Additional context**
the bidding timer bar seems to be anchored to the bidding window but the window dissapears after you close it and so does the anchor

**Comment by lantisnt** [comment]
Defered until GUI rework - bidding window can be reopened anytime.
