### ISSUE TITLE
Rename Minimum Points

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#424]
Pretty please? For my sanity as well as your own 🤣

**Comment by crimsoncoyote** [comment]
"Minimum points threshold" or something. Description to be something like "Minimum points remaining after bidding".
Perhaps also change the "Allow bidding more than current standings" to "Allow remaining points to go below threshold"

**Comment by crimsoncoyote** [comment]
I also wonder if there is a desire to allow bidding under threshold but NOT bidding negative because I think checking the box with a positive number in the min points box would allow you to bid negative, even if it's somewhat counter-intuitive.

**Comment by nickcec24** [comment]
i am having a problem with awarding gear after the bid of dkp it gives me an error message and does not take of the dkp or assign the item.
