### ISSUE TITLE
New item price feature

### ISSUE THREAD

**Issue by SaneSL** [ClassicLootManager/ClassicLootManager#425]
**Is your request related to a problem? Please describe.**
My guild uses a system where the price of the item will be 2nd highest bid + 1. For example A bids 7 and B bids 4, -> price = 5.
But if A bids 6 and nobody else bids -> price = 2

I guess the + 1 on the 2nd highest could also be defined by the raid leader.

Would it be possible to have this feature implemented?

Thanks

**Comment by crimsoncoyote** [comment]
This is already a feature. Add a value for Tax when using vickrey
