### ISSUE TITLE
item award

### ISSUE THREAD

**Issue by nickcec24** [ClassicLootManager/ClassicLootManager#426]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**AddOn and Game Version:**
 - 
 - 

**Additional context**

**Comment by nickcec24** [comment]
i am getting an error message when i try to award an item for dkp after the bidding , it wont deduct the dkp or award the item.

**Comment by lantisnt** [comment]
Click on player to select one to award
