### ISSUE TITLE
CEPGP Migrate Roster Glitch

### ISSUE THREAD

**Issue by psiven** [ClassicLootManager/ClassicLootManager#427]
**Describe the bug**
CEPGP migration created an invalid roster which broke tooltips and required a rollback.

**To Reproduce**
1. Run CEPGP migration tool, new roster is created as expected
2. Renamed roster to 'Weekend' (I suspect this is what went wrong)
3. Reload
4. Note that new roster does not appear in item tooltip values even when checked
5. Remove other rosters
6. Item tooltips now produce a LUA error citing roster array index is nil, adding new rosters and even deleting this one does not fix

**Expected behavior**
Migration created roster to coexist peacefully, OR to obliterate all others and stand on its own.
I suspect that it collided with an existing roster upon reload. Perhaps it would occur baseline for anyone who happens to have created a roster named 'CEPGP' previously.

**AddOn and Game Version:**
 - CLM 2.6.1
 - WotLKC 3.4.0 (46368)

**Comment by lantisnt** [comment]
This sounds like migration misuse because it shouldnt be executed if there are any events in the system (even if you dont have them they would be synced back to you). I would need to see the SV that Has this happening to determine anything
