### ISSUE TITLE
Filter standings

### ISSUE THREAD

**Issue by FluffyRBinkies** [ClassicLootManager/ClassicLootManager#428]
**Describe the bug**
In standings window, the filter option doesn't keep your selection on the next session. If you disconnect from the game, you must reapply everytime your selection.

**To Reproduce**
1. Go to CLM.
2. Click on Standing.
3. Filter a set of parameter.
4. Disconnect or quit the game.
5. Log in again.
6. Go back to Standing.
7. Filter has been reset.

**Expected behavior**
The filter parameter should not change each session. The selection should stay the same with current character. Each character should have different filter parameter  that stay saved after a disconnect.

**AddOn and Game Version:**
 - WoW V3.4.0.46368
 - CLM V2.6.1

**Comment by lantisnt** [comment]
I think this would get even more confusing for people as most already doesn't look at filters and get confused.
I will accept a PR for this as a configuration (local to user) but disabled by default. but it's not something I see worth spending time with all other stuff in the backlog.

If you wish to provide pr feel free to, if not, I'll close the issue later on.
