### ISSUE TITLE
Adjust Decay calculations

### ISSUE THREAD

**Issue by timj11dude** [ClassicLootManager/ClassicLootManager#430]
https://github.com/ClassicLootManager/ClassicLootManager/blob/c1427c50a0b733a86aacadf7e81bcaecc6796d82/Modules/RosterManager/Roster.lua#L255+5

Could the section of code use the minimum GP inside the calculation of the decay?

# Expected

Player with GP score of 300 and with a roster configuration setting Minimum GP to 250.
Applying a 50% decay will result in the player having a new GP of: 275

# Actual

Applying a 50% decay will result in the player having a new GP of: 250

# Outcome

As implemented, we had a situation where player1 had a higher PR than player2 before decay, but due to player2 having higher EP, and both players bottoming out at the set minimum 250 GP, the PR order reversed.

**Comment by timj11dude** [comment]
![image](https://user-images.githubusercontent.com/2091306/202050721-459d7ee9-f01f-435c-9bf5-0feaa69b5257.png)

CEPGP provides an option to decide how decay is applied with Minimum.

**Comment by timj11dude** [comment]
Thanks for your reply, and help in understanding the implementation decision. 

It was an oddity to see though, and trips up our raiders where we're all only waiting for BiS items atm.

If I may re-frame your response so it's communicable to my raiders; 

> The minimum GP * decay% determines the amount of GP one could spend in a raid week without it affecting next week's PR.

Would that be appropriate?

**Comment by psiven** [comment]
That spreadsheet is quite incorrect as far as describing how Cepgp decay functions with decay-free threshold enabled. This is how it works on GP1:

https://docs.google.com/spreadsheets/d/1NcR4s2RNdTNU8mWJC9NgDvHZd6QqZltT-l3ovP2DWFw/edit?usp=drivesdk
