### ISSUE TITLE
All in Error

### ISSUE THREAD

**Issue by nosirrahdrof** [ClassicLootManager/ClassicLootManager#432]
Raiders getting an error when using the All In button *only* after already winning an item using the all in button.  

https://discord.com/channels/813686248841019392/1042284025450086410/1042284025450086410

![Screenshot 2022-11-16 073133](https://user-images.githubusercontent.com/10930395/202193844-3f0a445a-3464-4890-8d3b-287e6f85bb85.png)

[ClassicLootManager.zip](https://github.com/ClassicLootManager/ClassicLootManager/files/10022094/ClassicLootManager.zip)

**Comment by lantisnt** [comment]
Closed as both me and the author were not able to recreate it.
