### ISSUE TITLE
Export Window blank

### ISSUE THREAD

**Issue by Freeworld66** [ClassicLootManager/ClassicLootManager#433]
**Describe the bug**
We recently had an issue where some of the EP of a single (returning) player got lost. No idea what caused it, but we would like to use the Export function in he future to be able to track EPGP-standings outside of the addon.
However, when trying to export, the window just turns blank and the data can't be copied.
This sometimes also already happens when changing the desired time range for the export.

**To Reproduce**
1. Right click on the minimap button
2. Click on 'Export'
3. Switch to tab 'Export'
4. Click on 'Export'
5. Blank window (Chat message reports a successful export)

**Expected behavior**
Get Data export in XML-format

**Screenshots**
![grafik](https://user-images.githubusercontent.com/115668792/202578562-ffbfb223-4df7-4733-a446-88b09ad739e4.png)

**AddOn and Game Version:**
 - 2.6.2

**Comment by lantisnt** [comment]
Which export type, roster, profiles and time range did you select? This looks like you did select time range with no data or no type. 

But what's important is that EP doesn't disappear. 100% of the time it's someone Trusted doing something that they shouldnt do and either blaming addon or not understanding they messed up. I suggest checking the audit and fixing the state by removing wrong events.

**Comment by Freeworld66** [comment]
There are no records of manual changes of EP for him and he was missing points from automatic boss kill bonuses that were awarded to everyone in the raid. No idea if there is a way to manipulate this without any traces...

You are right about the cause of the blank window. Even though the desired options showed as if they were selected, when i clicked on them again and ran the export it worked.

**Comment by lantisnt** [comment]
There is no way to do anything without trace. Addon is based on event sourcing. 

It doesnt need to be EP removal. It usually is removal from roster or profiles. It's impossible for auto awards not working for single person

**Comment by Freeworld66** [comment]
The auto awards worked, but he started the raid with 0 EP today, GP was correct.

So... Someone added a Profile to the Roster today. Maybe that was him, but the entry doesn't show whose profile it was.
I assume this would caise their EP to be reset?

**Comment by Freeworld66** [comment]
The auto awards worked, they just got lost when he started the raid today with 0/1.
I looked at the export and the missing points were in there so it seems someone might have removed him from the roster.
In the audit it doesn't show the player's name when a roster is edited. Would be useful to be able to see that.
Cheers

**Comment by lantisnt** [comment]
I agree audit is missing some data. You could try searching for removals from roster ans addings afterwards. Probably you will find him there indirectly (timetravel before the event happened to see if the was it)
