### ISSUE TITLE
Alt linking doesn't handle main change properly

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#435]
if we have 3 characters A B C
A is alt of B
and now we set A as alt of C
then B keeps information that A is his alt, while he is relinked to C

Either handle re-linking or disallow linking in this case until unlink happens

**Comment by hblGP** [comment]
I've experienced that it's not possible to link several alts to the same main. If I'm not mistaken then I think this should be a possibility.

I've only tried it once, and it seems like the linking get's ovewritten.

**Comment by lantisnt** [comment]
that sounds like player error - you **can** link multiple alts to the same main. problem in this issue exists if you link alt to a main without unlinking first

**Comment by hblGP** [comment]
Tested again, and it works as intended. I don't know what went wrong first time I attempted it, can't reproduce it so I think it's all good :).
