### ISSUE TITLE
Awarding items outside of raids

### ISSUE THREAD

**Issue by timj11dude** [ClassicLootManager/ClassicLootManager#436]
**Is your request related to a problem? Please describe.**
This isn't strictly an issue as it's reasonably easy to create a raid in CLM, form a quick party/raid with one other willing volunteer. However for testing, and handling out of raid transactions like allowing raiders to purchase items from the Guild Bank in exchange for GP.

**Describe the solution you'd like**
Preferable would be the removal of the restriction to be in a raid to be able to award items. (Understand that a Roster needs to be tracked for where EPGP needs to be assigned)
Alternatively, a method via the CLI option `/clm award` to specify the roster (perhaps by some shorthand id) and amount.
Alternatively, a new `Reason` option in the `Management` section of the `Standings` tab, to be able to assign manual item awards, with perhaps an autofill of the base/max GP cost for the item in the award value. (plus the auto selection of the Gear Points checkbox)

**Describe alternatives you've considered**
The alternatives I have are to create a "Shopping" raid, apply the overrides to disable the auto EP awards, form a raid with a fellow guildie, and handle all shopping in that window while the raid is running.
The other alternative, is to use the manual point adjustments option in the `Standings` view, but **this doesn't allow for tracking item awards** like normal raid awards do.

**Additional context**
Considering out of raid item awards, such as BoEs being offered to all of guild, and Ulduar guild crafted items.

**Comment by lantisnt** [comment]
Thanks for your request.
This feature already exists in CLM slash commands:
https://github.com/ClassicLootManager/ClassicLootManager/wiki/4.-Slash-Commands#award-item-without-auction
`/clm award Item Link/Value/Roster Name/Player`

In future a GUI is planned for it also but no ETA yet.

**Comment by timj11dude** [comment]
I can see that the UI has been added since: https://github.com/ClassicLootManager/ClassicLootManager/pull/438
