### ISSUE TITLE
Alt+clicking/adding items to auction window already-awarded don't show bids from most recent auction

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#446]
This is mostly an issue with duplicate items in a single auction, and workaround would be to uncheck the box to auto-clear awarded items, but requires remembering when there are duplicates of an item in bags (of which there may be many).

**Comment by lantisnt** [comment]
This is designed this way because once Item is removed from auction it's data is lost (except the part stored in history). You indeed should unselect the clear if you preffer to remove items manually.
