### ISSUE TITLE
Guild externals dont get the auction window anymore.

### ISSUE THREAD

**Issue by SimonDewert** [ClassicLootManager/ClassicLootManager#448]
**Describe the bug**
Raiders from an other guild, dont get the auction-popup anymore

**To Reproduce**

1. Create a Raid group with two different guilds
2. Create a Raid in clm, start the raid.
3. alt+click on an item

**Expected behavior**
All Raiders suitable for the item get the popup window.

**Screenshots**

**AddOn and Game Version:**
 - clm 3.0.0
 - wow 3.4.0.47168

**Comment by lantisnt** [comment]
Known issue. Will require significant work to reenable.
adding @crimsoncoyote as a watcher
