### ISSUE TITLE
CLM Export not working since 3.0

### ISSUE THREAD

**Issue by Pimpi18** [ClassicLootManager/ClassicLootManager#450]
**Describe the bug**
When i export XML, JSON or TMB i receive a LUA-Error

**To Reproduce**
1. Open Export Window with "clm export"
2. Check XML or TMB
3. Let Roaster and Profiles by all
4. On the Export Tab click Export

**Screenshots**
Message: ...tManager_Integrations/Models/ExportConfiguration.lua:13: attempt to index field 'FORMAT_VALUES' (a nil value)
Time: Wed Jan 18 08:30:47 2023
Count: 1
Stack: ...tManager_Integrations/Models/ExportConfiguration.lua:13: attempt to index field 'FORMAT_VALUES' (a nil value)

Locals: <none>

**AddOn and Game Version:**
 - AddOn Version 3.0
 - Game Version 3.4.1 (47612)
 - ElvUI 13.20

**Comment by lantisnt** [comment]
Fixed already on master branch.
