### ISSUE TITLE
After Update 3.0.1 Lua Error and no Roster

### ISSUE THREAD

**Issue by Pimpi18** [ClassicLootManager/ClassicLootManager#453]
**Describe the bug**
After i Update CLM from 3.0 to 3.0.1 i receive after login a lua-error and no roster configuration

**To Reproduce**
1. Close WoW
2. Update CLM to 3.0.1
3. Login

**Screenshots**
![image](https://user-images.githubusercontent.com/21289573/213197769-a73ea7db-627d-4189-8a52-c708b0b7f83f.png)
![image](https://user-images.githubusercontent.com/21289573/213197859-f0596f7f-d5ce-4110-9e9d-b728ea5f6c73.png)

**AddOn and Game Version:**
 - AddOn CLM 3.0.1
 - WoW Wotlk 3.4.1 (47612)
 - Ace3 1294
 - ElvUI 13.20

**Additional context**
`Message: ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:1854: AceConfigRegistry-3.0-21:ValidateOptionsTable(): Classic Loot Manager Änderungsprotokoll.args.version20v3.0.1header.args.Fixes1v3.0.1body.name: expected a string or funcref, got 'nil'
Time: Wed Jan 18 15:25:29 2023
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:1854: AceConfigRegistry-3.0-21:ValidateOptionsTable(): Classic Loot Manager Änderungsprotokoll.args.version20v3.0.1header.args.Fixes1v3.0.1body.name: expected a string or funcref, got 'nil'
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:211: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:206>
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:245: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:283: in function `ValidateOptionsTable'
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:325: in function `app'
[string "@Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1854: in function `Open'
[string "@Interface/AddOns/ClassicLootManager/Modules/Common/Changelog/GUI.lua"]:126: in function <.../ClassicLootManager/Modules/Common/Changelog/GUI.lua:70>
[string "@Interface/AddOns/ClassicLootManager/Modules/Common/Changelog/GUI.lua"]:133: in function `Create'
[string "@Interface/AddOns/ClassicLootManager/Modules/Common/Changelog/GUI.lua"]:62: in function `Initialize'
[string "@Interface/AddOns/ClassicLootManager/ClassicLootManager.lua"]:192: in function `?'
[string "@Interface/AddOns/ClassicLootManager/ClassicLootManager.lua"]:222: in function `_SequentialInitialize'
[string "@Interface/AddOns/ClassicLootManager/ClassicLootManager.lua"]:228: in function <...ace/AddOns/ClassicLootManager/ClassicLootManager.lua:228>

Locals: v = nil
oktypes = <table> {
 function = true
 string = true
 _ = "string or funcref"
}
errlvl = 6
isok = nil
type = <function> defined =[C]:-1
err = <function> defined @Interface/AddOns/Atlas/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:45
tostring = <function> defined =[C]:-1
`

**Comment by lantisnt** [comment]
Hotfix already building. Thanks for those reports 👍
