### ISSUE TITLE
Error when trading after item award

### ISSUE THREAD

**Issue by Fourchaise** [ClassicLootManager/ClassicLootManager#454]
After awarding an item in bags via auction, when opening an trade with the awarded player, the item is not put in the trade and i get the attacher error.
![clm trade error](https://user-images.githubusercontent.com/27202955/213313818-8d847d7b-c3e6-491b-9116-07c64ce452a3.jpg)

**Comment by Fourchaise** [comment]
Error happens when using the new direct award feature as well

**Comment by lantisnt** [comment]
Finally an actual error log!
Will be fixed tomorrow
