### ISSUE TITLE
Not auto trading won loot

### ISSUE THREAD

**Issue by captsausage** [ClassicLootManager/ClassicLootManager#458]
anyone else having this issue? im assigning loot to people but it wont auto open trade or even if i open a trade it wont throw it in the window like it used to. Works fine if im using /roll with gargul but CLM doesnt do this anymore

**Comment by crimsoncoyote** [comment]
What version are you on? There have been a few hotfixes for it.

**Comment by captsausage** [comment]
3.0.4

**Comment by crimsoncoyote** [comment]
Make sure you run `/console scriptErrors 1` (possibly reload ui after) and report any Lua errors. 

I think it's been reported elsewhere but I don't think there's been enough info yet.

**Comment by crimsoncoyote** [comment]
Pending trades won't persist after a reload as well, so just be aware

**Comment by lantisnt** [comment]
`v3.0.4` was confirmed to work. please be sure to use it. 

Also next time if reporting bug please add version number (even better with screenshot).
Reopen / start new issue if this happens on `v3.0.4` or newer.
