### ISSUE TITLE
I know this is probably the wrong place but...

### ISSUE THREAD

**Issue by Grizz2202** [ClassicLootManager/ClassicLootManager#459]
Can anyone tell me how to turn off the "auctioning" window that pops up when I alt+click something? It's doing it when I'm in the F'ing auction house and it's driving me crazy!!! Please help!

**Comment by Grizz2202** [comment]
This is what I'm talking about (I hope it goes through right). I alt click an item, the chat says "CLM Auctioning requires active raid or roster mode", but this stupid popup pops up anyway. I'm not an Officer in the guild, I just have this stupid thing because I need it to see my prio!! please make this stop.

![image](https://user-images.githubusercontent.com/50120234/214440410-73e56411-6256-4ecb-96d0-ff8b276a1898.png)

**Comment by lantisnt** [comment]
Jokes aside: are you in CLM raid? If not then that's an actual bug

**Comment by Grizz2202** [comment]
We do use CLM in raid, but I'm just a regular raider if that's what you mean.

**Comment by crimsoncoyote** [comment]
Yeah it happens to me just sitting in dal.
No raid
![image](https://user-images.githubusercontent.com/1790997/214441264-d3a51c31-59bd-4eed-a02b-944ee2dcd931.png)

**Comment by lantisnt** [comment]
> Yeah it happens to me just sitting in dal.
> No raid
> ![image](https://user-images.githubusercontent.com/1790997/214441264-d3a51c31-59bd-4eed-a02b-944ee2dcd931.png)
> 

On untrusted alt?

**Comment by crimsoncoyote** [comment]
Doesn't open with untrusted alt, only trusted.

**Comment by crimsoncoyote** [comment]
@Grizz2202 can you read officer notes in your guild? If so, the GM needs to change that.

**Comment by lantisnt** [comment]
> We do use CLM in raid, but I'm just a regular raider if that's what you mean. 

That means your are trusted from CLM perspective (can read or write officer notes). You want to followup with your Guild officers also as well you probably shouldn't

**Comment by Grizz2202** [comment]
I am able to see the O notes. I think we had to have that enabled for everyone in order for CEPGP to work (we're moving away from that to this addon instead). Do I need to ask them to re-restrict that?

**Comment by crimsoncoyote** [comment]
Yes, with that enabled you are a "trusted" person and would be able to start auctions.
It shouldn't open the UI unless you're in a CLM raid, so that part is a bug still.

**Comment by lantisnt** [comment]
Start auctions, Control EP/GP/dkp... Yeah they need to look at CLM ACL

**Comment by Grizz2202** [comment]
Thanks, I didnt know this was a bug and thought I was doing something wrong!
