### ISSUE TITLE
Change for CLM Minimap Button

### ISSUE THREAD

**Issue by J07-Zenith** [ClassicLootManager/ClassicLootManager#46]
**Is your feature request related to a problem? Please describe.**
Minimap button for CLM resets to original position after quitting the game.

**Describe the solution you'd like**
When the minimap button for CLM is moved it should remember the position, like minimap buttons for other addons.

**Describe alternatives you've considered**
An option in settings to hide the minimap button for CLM.

**Additional context**
n/a

**Comment by lantisnt** [comment]
Fixed in #72
