### ISSUE TITLE
Latest version installed. Nothing appears on screen. No minimap button. No /clm gui reponse. Tested as only addon. Same result. Other players can see me on their screens. I cannot get anything at all to show.

### ISSUE THREAD

**Issue by ianmw7** [ClassicLootManager/ClassicLootManager#471]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**AddOn and Game Version:**
 - 
 - 

**Additional context**

**Comment by lantisnt** [comment]
You want to check if its in the addon list - if its not you installed it wrong. My guess is you tried to manually install it and put in the CLM directory but in fact CLM is 3 separate addons.
