### ISSUE TITLE
Change cancel to pass and remove close button

### ISSUE THREAD

**Issue by SlowxP** [ClassicLootManager/ClassicLootManager#61]
Small suggestions I've talked with a friend about it, and we would love to have when auctioning items in the window where you can see the bidders we would like to see everyone in the raid and see who passes on loot by changing the button cancel to Pass and remove the close button. We feel that this will speed up the bidding as I didn't know if there would be any more bids for an item, but if people click pass I know how many are left and willing to bid!
And how to see who passes on loot would be either remove them from the list or give them a red name or something like that
or a text saying "Passed" besides their names. There are some options for it. Also, something I noticed when puging is that the pugs get added to your profiles and roster after starting the raid. Imo and maybe its bugged, but I think people should only get added to the roster if added manually.

**Comment by SamMousa** [comment]
Please make separate issues for separte things @SlowxP!

Also some enters can help with readability.

### Problem

All auctions need to run for the full duration even if everyone that wants to bid has done so.

### Proposed solution

- Add a `pass` button to make **not bidding** explicitly different from **passing**
- Show who passed in the auction UI
- Show who could still bid in the auction UI

Optionally:
- Remove `cancel` button and `x` closing options to force people to make a decision

**Comment by SlowxP** [comment]
Alright sry man, but your "proposed solution" is what we want! And also the "force people to make a decision" would be great!

**Comment by SamMousa** [comment]
Forcing people will be hard; what if you are mid fight and just need the window to go away etc..
First iteration I think we go with adding a pass button without removing other buttons.

That way we can gather some data and see how / if users use it.

**Comment by SlowxP** [comment]
Alright, better than nothing :)

**Comment by lantisnt** [comment]
My proposal for solution:

- [ ] Add a pass button to make not bidding explicitly different from passing
- [ ] Show who passed in the auction UI
- [ ] Disable closing bidding window by hitting ESC so there will not be any accidental closes

No enforcing and no bloating of the ui with people that didnt choose anything
