### ISSUE TITLE
Refactor CLM code

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#69]
Refactor CLM code to make it more human readable for the community to work on.
Refactor needs to be done in a smart way and only where needed.

Result must be:
1. Easily readable and understandable. Comments added where needed
2. Private and Public API must be separated
3. Functions must have known and constant or nil return type (function can return either type X or nil)

- [ ] ACL
- [ ] Comms
- [ ] Database #73 
- [ ] Logger
- [ ] AuctionManager and BiddingManager
- [ ] ConfigManager
- [ ] LedgerManager
- [ ] EventManager
- [ ] History
- [ ] LootManager
- [ ] PointManager
- [ ] ProfileManager
- [ ] RaidManager
- [ ] RosterManager and Standings
- [ ] VersioningManager
- [ ] Core files and directory structure
- [ ] Expose Public APIs for WA integration #85

**Comment by SamMousa** [comment]
- [ ] One file per `class`? 
- [ ] Naming convention for (public) functions: `UpperCamelCase`
- [ ] Naming convention for (public) function arguments: `...`

**Comment by lantisnt** [comment]
Closing issue. Will rework it into Project `soon`
