### ISSUE TITLE
Show bidders how much DKP they have left!

### ISSUE THREAD

**Issue by SlowxP** [ClassicLootManager/ClassicLootManager#76]
I have another idea to make biding maybe go faster. Somewhere in the bidding window for the raiders to see how much DKP they have, so they don't have to re-open the DKP window. Because as a LM I forgot that they can't see the small window with bids and how much they have, that's only me who can see that. Might speed up the biding if you could see how much they have and maybe how much the others biding have.

**Comment by roaspeci** [comment]
++ would be nice

**Comment by SamMousa** [comment]
Please use the thumbs up emoticons @roaspeci. No need to spam.

**Comment by lantisnt** [comment]
Covered by #106
