### ISSUE TITLE
Make 'Max' button on bid screen work with a users current dkp standings

### ISSUE THREAD

**Issue by davierik** [ClassicLootManager/ClassicLootManager#79]
The 'Max' button on the bid screen is based on the maximum dkp cost configured for an item in Ascending auction mode. However, the default value for this, and probably most commonly used(?), is 0, in order to not set a max bid value, but rather let users bid as much as they want/have. In this situation, a user might expect the 'Max' button to auto-bid with all their DKP. In reality, sets the value to/tries to bid 0.

As a solution to this, I believe it would be better if the button worked as such:
if ( item_max = 0) bid_value = user_dkp
else bid_value = min(item_max, user_dkp)

I.e., make the max bid work with the user's current dkp standings, and, if a max value _has_ been defined, restrict the bid within the allowed range.

This would also go a bit along the way to deal with #76 .

**Comment by roaspeci** [comment]
++ would be nice

**Comment by lantisnt** [comment]
This description is re-described behavior that I have implemented and was then incorporated in CommunityDKP. That was a solution that i find very unclear as it would bid different value for different item settings thus button behavior changes dynamically. We will be reworking the GUI soon thus will think about incorporating max current dkp in the bid window in some way.

**Comment by lantisnt** [comment]
Max and Base buttons will be disabled if related value is set to 0 (disabled)
