### ISSUE TITLE
Right-click on Raid when Raid is already selected removes selection

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#81]
**Describe the bug**
If you click a raid in the Raid Manager UI, then right-click the same raid to start/end/join the raid, the raid becomes deselected and the start/end/join buttons do not work because no raid is selected. If you try to left-click the raid to select it again, the context menu goes behind the Raid Manager UI and cannot be clicked.

**To Reproduce**
1. Create a raid in the Raid Manager
2. Left-click the raid to select it
3. Right-click the selected raid
4. Attempt to start the raid

**Expected behavior**
A selected raid in the Raid Manager should remain selected when right-clicked.

**AddOn and Game Version:**
CLM 0.7.0

**Comment by lantisnt** [comment]
Covered by #88
