### ISSUE TITLE
Add confirmation dialog with actual bid value when submitting bid

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#82]
**Is your feature request related to a problem? Please describe.**
We've had a couple instances where bidders thought they were bidding a value other than the base value, or weren't sure if their bid was submitted since the bid UI doesn't change after a bid. Users frequently seem to miss the small "Okay" button on the value field in the bid interface to lock in their change and will click "bid" with just the base value. The chat message that says a bid is accepted is not obvious enough, especially if the chat window is busy, and can result in "wait I thought I bid X not Y!"

**Describe the solution you'd like**
I would like to see a dialog pop up when clicking one of the bidding options to submit a bid that says something like "Submit X bid for Y item" with submit/cancel buttons.

**Describe alternatives you've considered**
- Update the bidding UI to show whether or not a bid is accepted and for how much
- Possibly remove the "Okay" to update the bid value and instead just take whatever bid value is in the bid field when selecting the "bid" button, especially if a confirm bid dialog is added

**Comment by roaspeci** [comment]
This should be a User Opt-in only because it Costs time

**Comment by SamMousa** [comment]
I think confirmation is a bad solution on this case. Since you can adjust your bid anyway.. instead we need to improve the UX so that users bid what they expect.

Why is the okay button next to the input needed at all?

**Comment by crimsoncoyote** [comment]
I agree that confirmation could be too much, especially if bids can be adjusted. Removing the "okay" would probably go a long way: what you see in the input field should be what you bid.

**Comment by lantisnt** [comment]
👎 when it comes to confirmation people do get the value as feedback in chat message. dont think dialog to confirm it is needed
