### ISSUE TITLE
Do Not require an enter/Done on values 

### ISSUE THREAD

**Issue by roaspeci** [ClassicLootManager/ClassicLootManager#84]
If I want to Award or adjust DKP or Change DKP value of items in Award Screen or If i want to bid a DKP value Not prefilled the UI requires an enter/Done. To use the UI in an easier way there should Not be a necessary "enter" on values

**Comment by lantisnt** [comment]
This will not be changed unless we change the GUI engine which wont come soon.

Remember that pressing `Enter` after putting value in also works
