### ISSUE TITLE
Create, Start & End Raids automatically 

### ISSUE THREAD

**Issue by roaspeci** [ClassicLootManager/ClassicLootManager#85]
If I enter a raid Zone as raidlead i want to Pop Up a Dialog Like "you want to start a DKP raid and add Missing Players" and Same If a leave it.

This could be an opt in Feature per user

**Comment by SamMousa** [comment]
These kinds of ideas are really interesting, but also there is no limit to these requests.

Would using a tool like WeakAuras not solve this problem?

We could expose some functions for use with the custom function functionality, that way you could easily create your own WA automations and trigger them when / if you want to.

**Comment by roaspeci** [comment]
Sounds great and coulb be a nice Interim solution

**Comment by lantisnt** [comment]
I like the exposing APIs idea. That's definitely something we should add to our refactor plans @SamMousa

**Comment by lantisnt** [comment]
I think this should be one of the great use cases of external API and is one of the reasons we should introduce it.
