### ISSUE TITLE
Everything just reset this week,

### ISSUE THREAD

**Issue by ideaBlender** [ClassicLootManager/ClassicLootManager#89]
**Describe the bug**
Everything just reset this week, we had a month or raid history, no longer visible

**To Reproduce**
not sure if i can

**Expected behavior**
Addon should retain loot history

**Screenshots**
Loot history now only shows this work

**AddOn and Game Version:**
 - Addon: 0.7.0
 - TBC Classic latest 2.5.1

**Additional context**

**Comment by lantisnt** [comment]
Please provide more detailed information and attach savedvariable file.

**Comment by SamMousa** [comment]
@lantis, was this resolved? Please leave a comment to tell future Googlers what happened!
