### ISSUE TITLE
Cap on weekly DKP reward

### ISSUE THREAD

**Issue by Ivolution85** [ClassicLootManager/ClassicLootManager#9]
Within Essential, DKP that can be earned per week, is capped to 20 DKP (10 DKP per evening), even if a person would be on the bench for a 3rd night. In TBC, we foresee the possibility of having a cap of 20 DKP even if a person raids 3 nights (2 evenings of Kara, 1 for Gruul).

Could we make it so that that weekly DKP gain is capped to a certain amount?

Example:
1. Bob gets 10 DKP on Wednesday for joining Kara, first couple bosses
2. Bob gets 10 DKP on Thursday for joining Gruul.
3. Bob would get 10 DKP on Monday for joining Kara continuation, but that would be >20 DKP, so he doesn't actually get the DKP added.

The big advantages of this weekly cap are:
A. The DKP-awarder doesn't have to check for every individual in the raid whether he got DKP-to-cap already. Can simply award the same amount of DKP to everybody in the raid.
B. When applying DKP for Bench, it doesn't matter if you accidentally also give to somebody who was also in the raid.

**Comment by Ivolution85** [comment]
And because of the way the addon works, if the 2nd entry "Bob gets 10 DKP on Thursday for joining Gruul" is ignored from the calculation, Bob's weekly total would still be 20 DKP, because the 3rd entry ("Monday Kara continuation") would then 'become active' (no longer affected by the cap).

**Comment by Ivolution85** [comment]
For clarification: the weekly cap would be per raid week (so starting on Wednesday in the EU).

**Comment by lantisnt** [comment]
Week will start on weekly reset. 
It will be based on `GetServerTime()` thus linux epoch.
We will do a week number calculation based on reset time offsets from GMT
`543600 EU`
`486000 US`
