### ISSUE TITLE
Bid 1 without changing input not recognized by ML

### ISSUE THREAD

**Issue by JaMalchow** [ClassicLootManager/ClassicLootManager#91]
**Descr**
When bidding '1', without changing input value from the default '1', bid is not seen by ML. 
The bid (1) is accepted in chat but not seen by ML at end of auction.

**Workaround;**
User changes input value and press the (now visible) 'Okay'-button before pressing 'Bid'.

**To Reproduce**
1. Pop loot auction
2. Click Bid
3. Wait for auction to end

**AddOn and Game Version:**
v. 0.7.0. by user

**Additional context**
An easy fix could be having an empty default value in the window instead of '1'

Issue observed several times, latest in raid Apple 01-09-21. Have not actively tried to reproduce.

**Comment by lantisnt** [comment]
@JaMalchow Sorry but I was not able to reproduce it. When I press **bid** after getting the popup (not touching the settings) i do get the bid in auction window.

Please be sure to check if when you  bid you get bid accepted confirmation
![image](https://user-images.githubusercontent.com/43088589/132995144-53e2dc88-a6b8-408d-8cd9-d51bffe9dea7.png)
